server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/blog?currentSchema=blog
  jpa:
    database: postgresql
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    show-sql: true